### make train list text file

In [1]:
import os 

os.getcwd()

'/kwjin/EAGRNet'

In [4]:
import os
root_dir = './nia_8_inference/'
src_dir = 'train/images'
train = os.listdir(os.path.join(root_dir,src_dir))

print(len(train))

FileNotFoundError: [Errno 2] No such file or directory: './nia_8_inference/train/images'

In [5]:
f = open(root_dir+"/train_id.txt",'w')
for i in range(len(train)) :
    f.write(train[i].split(".")[0]+"\n")
f.close()

### make test list text file

In [12]:
root_dir = './nia_8_inference/test_init_data'
src_dir = '/test/images'
test = os.listdir(os.path.join(root_dir + src_dir))
print(len(test))

100


In [8]:
edges = os.listdir(os.path.join(root_dir + '/test/edges'))
labels = os.listdir(os.path.join(root_dir + '/test/labels'))


In [10]:
for i in range(len(edges)):
    if edges[i] != labels[i] and edges[i] !=test[i]:
        print('e')
    print(edges[i], labels[i], test[i])

0.grayscale.png 0.grayscale.png 0.png
10.grayscale.png 10.grayscale.png 10.png
100.grayscale.png 100.grayscale.png 100.png
110.grayscale.png 110.grayscale.png 110.png
120.grayscale.png 120.grayscale.png 120.png
130.grayscale.png 130.grayscale.png 130.png
140.grayscale.png 140.grayscale.png 140.png
150.grayscale.png 150.grayscale.png 150.png
160.grayscale.png 160.grayscale.png 160.png
170.grayscale.png 170.grayscale.png 170.png
180.grayscale.png 180.grayscale.png 180.png
190.grayscale.png 190.grayscale.png 190.png
20.grayscale.png 20.grayscale.png 20.png
200.grayscale.png 200.grayscale.png 200.png
210.grayscale.png 210.grayscale.png 210.png
220.grayscale.png 220.grayscale.png 220.png
230.grayscale.png 230.grayscale.png 230.png
240.grayscale.png 240.grayscale.png 240.png
250.grayscale.png 250.grayscale.png 250.png
260.grayscale.png 260.grayscale.png 260.png
270.grayscale.png 270.grayscale.png 270.png
280.grayscale.png 280.grayscale.png 280.png
290.grayscale.png 290.grayscale.png 290.png


In [6]:
f = open(root_dir+"/test_id.txt",'w')
for i in range(len(test)) :
    f.write(test[i].split(".")[0]+"\n")
f.close()

In [21]:
import cv2
import os
import numpy as np

print(os.getcwd())
img = cv2.imread('./16bit.png',cv2.IMREAD_ANYDEPTH)
print(np.shape(img))

# img_cut = img.astype(uint)

/kwjin/EAGR/EAGRNet
(1728, 1080)
0


In [24]:
print(img[0][0])

0


In [22]:
for i in range(len(img)):
    print(img[i].max(), len(img[i]))

0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0


In [25]:
img = cv2.imread('./16bit.png')


In [40]:
for i in range(len(img)):
    print(img[i].max())

0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0


In [38]:
print(img[0])
print(type(img))

[[0 0 0]
 [0 0 0]
 [0 0 0]
 ...
 [0 0 0]
 [0 0 0]
 [0 0 0]]
<class 'numpy.ndarray'>


In [39]:
a = [[1, 2, 3],[6,7,8]]
a= np.array(a)
print(a)
print(a.max())

[[1 2 3]
 [6 7 8]]
8
